<?php  //[STAMP] 1204a8bf5a3b6df1420fb8af69a954f2
// phpcs:ignoreFile
namespace api\tests\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build

trait UnitTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
